version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend-final
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - DB_PATH=/app/backend/data/database.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend-final
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge